[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Roshan Khilnani"
version = "2407-1"
description = "A simple example package"
authors = [{ name = "Roshan Khilnani", email = "rpkhilnani@yahoo.in" }]
license = { text = "GPL-3.0 license" }
